export const colors = {
  brand: {
    primary: "#ACA58A",
    // ファーストリリース後のカラー変更時に、こちらがメインになる
    primary2: "#3C3C3C",
  },
  main: {
    secondary: "#3C3C3C",
    grey: "#828282",
    cream: "#F9F7F2",
    white: "#FFFFFF",
    yellow: "#F2C94C",
    anidealGreen2: "#2ECEB9",
    haruzoraBlue: "#C3D9ED",
    haruzoraDark: "#70A8DC",
    sunsetPink: "#FAD5CD",
    yofukashiPurple: "#C6AEC7",
    yofukashiDark: "#A578A7",
    harukazeBlue: "#F0FFFE",
    akanePink: "#F9D2DD",
    illumiPink: "#EBB8C7",
  },
  text: {
    black: "#3C3C3C",
    white: "#FFFFFF",
    grey: "#828282",
    link: "#0071C1",
    attention: "#E8204E",
    disabled: "#BDBDBD",
  },
  action: {
    danger: "#E44343",
    success: "#6CCF59",
  },
  components: {
    defaultBackground: "#FFFFFF",
    background: "#EEEEEE",
    darkBackground: "#E0E0E0",
    mobileAppBackground: "#F6F6F6",
    overBackground: "#F2F2F2",
    disabled: "#F6F6F6",
    head: "#BDBDBD",
    border: "#BDBDBD",
    rating: "#FFC107",
    bottomSeparator: "#F0F0F0",
    lightBackground: "#FAFAFA",
  },
  activeBackground: "rgba(60, 60, 60, 0.1)",
};
